### ISSUE TITLE
error: unrecognized arguments: --generate-galaxy-xml

### ISSUE THREAD

**Issue by zfrenchee** [erasche/gxargparse#30]
Hi Eric, 
I'm ashamed to admit, I'm not exactly sure how to use this code. I don't think its explicitly specified anywhere. I have a program, which I've stripped down to just the argument parser, and I want to generate xml for it. Am I supposed to run the program without specifying the flags?

`python parseME.py --generate-galaxy-xml`

Or should I specify the flags as well? Does the program need to terminate successfully in order to generate the xml? Where does the xml get generated?

**Comment by erasche** [comment]
Hi @zfrenchee, the flag is `--generate_galaxy_xml`, sorry fo rthe confusion.

**Comment by erasche** [comment]
The XML generated will be sent to stdout, and the program will execute immediately, rather than allowing processing to continue. You do not need to specify any flags other than this one.

I'm sorry for the lack of documentation, it was a neat hack and I haven't worked on it much since. I'm hoping to get back to it eventually but I don't have a timeline for it right now.

**Comment by zfrenchee** [comment]
Ahh, I'm so sorry, that was stupid.
